export type GodModeLayerStatus = "unknown" | "blocked" | "planned" | "active";
export type GodModeTaskStatus = "blocked" | "r0-gate" | "todo" | "done";
export type GodModePriority = "P0" | "P1" | "P2" | "P3" | "P4";
export type GodModeLayerId = "L0" | "L1" | "L2" | "L3" | "L4" | "L5" | "L6";

export type GodModeLayer = {
  id: GodModeLayerId;
  name: string;
  color: string;
  status: GodModeLayerStatus;
  icon: string;
  components: Array<{
    name: string;
    detail: string;
  }>;
};

export type GodModeTask = {
  id: string;
  p: GodModePriority;
  title: string;
  cmd: string;
  status: GodModeTaskStatus;
  agent: string;
  layer: GodModeLayerId;
};

export type GodModeQueueSummary = {
  total: number;
  blocked: number;
  r0Gated: number;
};

export type GodModePocketHatcheryRelease = {
  score: number;
  scoreMax: number;
  status: "local-evidence-ready";
  externalWrites: false;
  evidenceFiles: string[];
  blockedGates: string[];
  nextAction: string;
};

export type GodModeActiveGoalIndex = {
  status: "in_progress_not_complete";
  claimsAllChatsRead: false;
  evidenceBoundary: "local_evidence_only";
  currentActionablePacket: "packet_013";
  externalWrites: false;
  lane2Authorized: false;
  blockers: string[];
  evidenceFiles: string[];
  nextAction: string;
};

export type GodModeCodexHermesQueueItem = {
  id: string;
  priority: GodModePriority;
  owner: "Hermes" | "Codex" | "Operator" | "Hermes / Codex";
  status: string;
  gate: string;
  nextAction: string;
  evidence: string[];
  blockedBy: string[];
  allowedActions: string[];
  forbiddenActions: string[];
  currentActionablePacket?: "packet_013";
  lane2Authorized?: false;
};

export type GodModeCodexHermesExecutionQueue = {
  status: "active_local_only";
  evidenceBoundary: "local_evidence_only";
  claimsAllChatsRead: false;
  lane2Authorized: false;
  runtimeQueueExecution: false;
  externalWrites: false;
  items: GodModeCodexHermesQueueItem[];
  evidenceFiles: string[];
  nextAction: string;
};

export type GodModeCodexHermesA2AQueueStatus = {
  status: "local_queue_indexed_not_executed";
  evidenceBoundary: "local_file_bus_only";
  currentActionablePacket: "packet_013";
  currentActionablePacketFolder: "inbox";
  runtimeQueueExecution: false;
  hermesDecisionRecorded: false;
  lane2Authorized: false;
  externalWrites: false;
  packetCounts: {
    inbox: number;
    outbox: number;
    working: number;
    done: number;
    blocked: number;
    total: number;
  };
  evidenceFiles: string[];
  nextAction: string;
};

export const GOD_MODE_LAYERS: GodModeLayer[] = [
  {
    id: "L0",
    name: "Hardware Foundation",
    color: "#7c3aed",
    status: "unknown",
    icon: "HW",
    components: [
      {
        name: "sirinx-control - Mac Mini M2",
        detail:
          "LiteLLM :4000 - Qwen3-35B :8080 - MySQL :3310 - Redis - n8n :5678 - Ollama :11434",
      },
      {
        name: "sirinx-worker-gpu - Windows PC",
        detail: "GPU inference worker - deepseek / heavy batch jobs",
      },
    ],
  },
  {
    id: "L1",
    name: "GhostClaws Core",
    color: "#ec4899",
    status: "blocked",
    icon: "GC",
    components: [
      {
        name: "LANE_HERMES_COMMANDER_A2A2A",
        detail: "89-file multi-agent orchestration scaffold",
      },
      {
        name: "A2A2A Active Worker Bridge",
        detail: "Node.js ESM dispatcher/worker - R0 gate: git push v0.1.0 pending",
      },
      {
        name: "Night Watch",
        detail: "BLOCKED - ERR_PNPM_ABORTED_REMOVE_MODULES_DIR - stale: 2026-06-27 03:49",
      },
      {
        name: "Security Hardening",
        detail: "Agent Lethal Trifecta audit - network egress allowlist - command broker policies",
      },
    ],
  },
  {
    id: "L2",
    name: "LatentMAS Transport",
    color: "#f59e0b",
    status: "planned",
    icon: "KV",
    components: [
      {
        name: "KV Latent Memory Bus",
        detail: "Replace text hop with hidden_states + past_key_values - target token reduction and speedup require benchmark proof",
      },
      {
        name: "Alignment Matrix Wa",
        detail: "Ridge-regression pseudo-inverse - Wa = (1/beta) * inv(Wout.T @ Wout + lambdaI) @ Wout.T @ Win",
      },
      {
        name: "Sequential Pipeline",
        detail: "Planner -> Critic -> Refiner -> Solver - decode text only at final agent",
      },
      {
        name: "Latent Steps",
        detail: "m = 0 / 10 / 20 / 40 / 80 - benchmark before claiming plateau behavior",
      },
      {
        name: "Backbone",
        detail: "Qwen3 local endpoint + Llama3 candidate path - verify model compatibility before transport work",
      },
    ],
  },
  {
    id: "L3",
    name: "Oracle Memory + Identity",
    color: "#10b981",
    status: "planned",
    icon: "MEM",
    components: [
      {
        name: "Psi Vault - MySQL :3310",
        detail: "Soft delete only - Nothing is Deleted principle - inbox / memory / retrospectives / trace / handoff",
      },
      {
        name: "Semantic Search",
        detail: "SQLite FTS5 + LanceDB hybrid - indexed target requires local proof - audit log on every AI search",
      },
      {
        name: "MCP Tools (23)",
        detail: "oracle_search - oracle_reflect - oracle_learn - oracle_handoff - oracle_inbox - oracle_trace - oracle_thread - oracle_schedule",
      },
      {
        name: "Identity Routing",
        detail: "21-agent SIRINX map - named agents are routing primitives, not anonymous worker IDs",
      },
      {
        name: "5 Principles + Rule 6",
        detail: "Nothing is Deleted - Patterns > Intentions - External Brain - Curiosity Creates - Form & Formless - Transparency",
      },
    ],
  },
  {
    id: "L4",
    name: "KOB CLI Skills Layer",
    color: "#3b82f6",
    status: "active",
    icon: "KOB",
    components: [
      {
        name: "5-Phase Rollout",
        detail: "P1 kobdemy -> P2 -> P3 -> P4 -> P5 GhostClaws",
      },
      {
        name: "13 Custom Skill Gaps",
        detail: "From SIRINX_AGM_KOB_SKILLS_MASTERPLAN.md - mapped to 3-phase AGM timeline",
      },
      {
        name: "Cross-agent Portability",
        detail: "Claude Code - Codex - Cursor - OpenCode - Gemini CLI - agent-agnostic workflow",
      },
      {
        name: "UiPath AgentHack Track 2",
        detail: "Open item - needs timeline",
      },
    ],
  },
  {
    id: "L5",
    name: "SIRINX Business Intelligence",
    color: "#f97316",
    status: "active",
    icon: "BI",
    components: [
      {
        name: "Solar Tariffs (hardcoded)",
        detail: "Peak 4.18 / Off-peak 2.65 / VSPP 2.20 THB/kWh - Phitsanulok 65000 - 600/99 Midtrapab Rd.",
      },
      {
        name: "150% Tax Shield Product Suite",
        detail: "Smart Solar - Solar Carport - EV Charging - BESS - AI Agentforce - Robotics",
      },
      {
        name: "Zero CapEx / PPA",
        detail: "Targets: industrial factories - hotels - hospitals - commercial buildings",
      },
      {
        name: "AGM Galaxy",
        detail: "Alpha Gene Record Media - YouTube: @alphagenerecordmedia - parallel creative venture",
      },
    ],
  },
  {
    id: "L6",
    name: "Pocket Hatchery MVP",
    color: "#14b8a6",
    status: "active",
    icon: "PH",
    components: [
      {
        name: "Creature Catalog",
        detail: "Deterministic creatures - egg -> hatch -> evolve; no paid randomness",
      },
      {
        name: "Wallet Flow",
        detail: "Public: WAX Cloud Wallet / My Cloud Wallet. Office-internal signer stays out of public surfaces.",
      },
      {
        name: "Contract Actions",
        detail: "mintCreature, feed, evolve, pause, unpause - testnet-first, no loot box / cash-out.",
      },
      {
        name: "Release Gate",
        detail: "Score 84/100 local evidence ready - R0 deploy and real wallet connector still blocked.",
      },
    ],
  },
];

export const GOD_MODE_QUEUE: GodModeTask[] = [
  {
    id: "P0-1",
    p: "P0",
    title: "Fix Night Watch pnpm",
    cmd: "Manual remediation draft only: rm -rf node_modules && pnpm install --frozen-lockfile && pnpm night-watch",
    status: "blocked",
    agent: "Claude Code",
    layer: "L1",
  },
  {
    id: "P0-2",
    p: "P0",
    title: "Hermes Stack Health Check",
    cmd: "curl :4000/health && curl :5678/healthz && curl :8080/v1/models && redis-cli ping",
    status: "blocked",
    agent: "Claude Code",
    layer: "L0",
  },
  {
    id: "P1-1",
    p: "P1",
    title: "Test Qwen3 hidden_states access",
    cmd: "python3 -c \"from transformers import AutoModelForCausalLM; m=AutoModelForCausalLM.from_pretrained('Qwen/Qwen3-4B-Instruct'); print(m.config)\"",
    status: "todo",
    agent: "Claude Code",
    layer: "L2",
  },
  {
    id: "P1-2",
    p: "P1",
    title: "Psi Vault schema - MySQL :3310",
    cmd: "CREATE TABLE oracle_memory (id BIGINT AUTO_INCREMENT, agent_name VARCHAR(64), session_id VARCHAR(128), content TEXT, embedding BLOB, is_deleted BOOL DEFAULT 0 ...)",
    status: "todo",
    agent: "Claude Code",
    layer: "L3",
  },
  {
    id: "P1-3",
    p: "P1",
    title: "Unblock A2A2A Worker Bridge R0",
    cmd: "git push Agent Bridge v0.1.0 - HUMAN APPROVAL REQUIRED",
    status: "r0-gate",
    agent: "Pitoon",
    layer: "L1",
  },
  {
    id: "P2-1",
    p: "P2",
    title: "LatentMAS: Wa alignment matrix",
    cmd: "python3 latent_backend/alignment.py --model Qwen/Qwen3-4B --cache-wa True",
    status: "todo",
    agent: "Claude Code",
    layer: "L2",
  },
  {
    id: "P2-2",
    p: "P2",
    title: "Wire Oracle MCP to GhostClaws n8n",
    cmd: "n8n webhook /oracle/search -> MCP adapter -> oracle_search tool",
    status: "todo",
    agent: "Claude Code",
    layer: "L3",
  },
  {
    id: "P2-3",
    p: "P2",
    title: "KOB CLI P1 kobdemy launch",
    cmd: "kob init kobdemy && kob skill add recap rrr trace learn forward",
    status: "todo",
    agent: "Claude Code",
    layer: "L4",
  },
  {
    id: "P3-1",
    p: "P3",
    title: "LatentMAS sequential prototype",
    cmd: "cargo run -p katgpt-orchestrator -- bench --model Qwen/Qwen3-4B --mode latentmas --latent-steps 40 --agents planner,critic,refiner,solver",
    status: "todo",
    agent: "Claude Code",
    layer: "L2",
  },
  {
    id: "P3-2",
    p: "P3",
    title: "Rust orchestrator scaffold",
    cmd: "cargo new katgpt-latentmas && mkdir -p crates/katgpt-orchestrator/src crates/latent-protocol/src python/latent_backend",
    status: "todo",
    agent: "Claude Code",
    layer: "L2",
  },
  {
    id: "P3-3",
    p: "P3",
    title: "GhostClaws Mission Control deploy",
    cmd: "R0 gate - production deploy requires Pitoon approval",
    status: "r0-gate",
    agent: "Pitoon",
    layer: "L1",
  },
  {
    id: "P4-1",
    p: "P4",
    title: "21-agent identity routing wire-up",
    cmd: "Full SIRINX agent map -> LiteLLM routing -> model score table",
    status: "todo",
    agent: "Multi-agent",
    layer: "L3",
  },
  {
    id: "P4-2",
    p: "P4",
    title: "Federation: M2 + GPU worker",
    cmd: "maw federation HMAC-SHA256 - config sirinx-control peer sirinx-worker-gpu",
    status: "todo",
    agent: "Multi-agent",
    layer: "L0",
  },
  {
    id: "P4-3",
    p: "P4",
    title: "AGM Galaxy creative agent pipeline",
    cmd: "AGM agent + YouTube workflow + @alphagenerecordmedia automation",
    status: "todo",
    agent: "Claude Code",
    layer: "L5",
  },
  {
    id: "P1-4",
    p: "P1",
    title: "Pocket Hatchery: creature catalog schema + deterministic state machine",
    cmd: "Implement apps/pocket-hatchery/ data schemas and state machine",
    status: "done",
    agent: "Codex",
    layer: "L6",
  },
  {
    id: "P2-4",
    p: "P2",
    title: "Pocket Hatchery: contract action table + wallet flow",
    cmd: "Document safe contract actions and public wallet path",
    status: "done",
    agent: "Opus",
    layer: "L6",
  },
  {
    id: "P0-3",
    p: "P0",
    title: "Pocket Hatchery: security sentinel - public signer exposure",
    cmd: "Run WORKSPACE_SCAFFOLD/tests/test_public_signer_exposure.py and evidence JSON",
    status: "done",
    agent: "Hermes",
    layer: "L6",
  },
  {
    id: "R0-PH-1",
    p: "P1",
    title: "Pocket Hatchery: R0 testnet deploy",
    cmd: "R0 gate - testnet deploy requires Pitoon approval",
    status: "r0-gate",
    agent: "Pitoon",
    layer: "L6",
  },
];

export const GOD_MODE_R0_GATES = [
  "git push - Agent Bridge v0.1.0",
  "GitHub Release publish",
  "GhostClaws Mission Control production deploy",
  "Hermes Kanban first real run",
  "osmGemma LaunchAgent load",
  "Pocket Hatchery testnet deploy",
  "Pocket Hatchery mainnet deploy",
  "Pocket Hatchery real wallet connector",
] as const;

export const GOD_MODE_POCKET_HATCHERY_RELEASE: GodModePocketHatcheryRelease = {
  score: 84,
  scoreMax: 100,
  status: "local-evidence-ready",
  externalWrites: false,
  evidenceFiles: [
    "apps/pocket-hatchery/ops/wallet_flow_evidence.md",
    "apps/pocket-hatchery/ops/metadata_permission_audit.md",
    "apps/pocket-hatchery/ops/rollback_plan_review.md",
    "WORKSPACE_SCAFFOLD/tests/test_release_gate_score.py",
  ],
  blockedGates: ["testnet deploy", "real wallet connector", "production deploy", "git push / merge"],
  nextAction: "Review read-only evidence in Mission Control; keep R0 gates blocked until exact approval.",
};

export const GOD_MODE_ACTIVE_GOAL_INDEX: GodModeActiveGoalIndex = {
  status: "in_progress_not_complete",
  claimsAllChatsRead: false,
  evidenceBoundary: "local_evidence_only",
  currentActionablePacket: "packet_013",
  externalWrites: false,
  lane2Authorized: false,
  blockers: [
    "BLOCK-CHAT-EXPORT",
    "BLOCK-LANE1-OPUS-PACKET",
    "BLOCK-HERMES-GATEWAY",
    "BLOCK-V3-3-ARTIFACT",
    "BLOCK-R0-APPROVALS",
  ],
  evidenceFiles: [
    "data/pathspecs/sirinx_active_goal_systematic_work_index_2026-06-29.json",
    "docs/knowledge/SIRINX_ACTIVE_GOAL_SYSTEMATIC_WORK_INDEX_2026-06-29.md",
    "data/pathspecs/sirinx_hermes_codex_a2a_godmode_v3_html_recheck_2026-06-29.json",
    "data/pathspecs/sirinx_all_chat_export_intake_mapper_2026-06-29.json",
    "data/pathspecs/sirinx_active_goal_blocker_clearance_validator_2026-06-29.json",
    "WORKSPACE_SCAFFOLD/scripts/probe_active_goal_blockers.py",
    "data/pathspecs/sirinx_active_goal_read_only_probe_runner_2026-06-29.json",
    "docs/knowledge/SIRINX_ACTIVE_GOAL_READ_ONLY_PROBE_RUNNER_2026-06-29.md",
    "WORKSPACE_SCAFFOLD/reports/active_goal_read_only_probe_latest_2026-06-29.json",
    "data/pathspecs/sirinx_active_goal_completion_requirements_matrix_2026-06-29.json",
    "docs/knowledge/SIRINX_ACTIVE_GOAL_COMPLETION_REQUIREMENTS_MATRIX_2026-06-29.md",
    "data/pathspecs/sirinx_codex_hermes_work_report_contract_2026-06-29.json",
    "data/pathspecs/sirinx_active_goal_source_file_receipt_2026-06-29.json",
    "docs/knowledge/SIRINX_ACTIVE_GOAL_SOURCE_FILE_RECEIPT_2026-06-29.md",
    "data/pathspecs/sirinx_codex_hermes_a2a_queue_status_2026-06-29.json",
    "docs/knowledge/SIRINX_CODEX_HERMES_A2A_QUEUE_STATUS_2026-06-29.md",
    "WORKSPACE_SCAFFOLD/reports/codex_hermes_a2a_queue_status_latest_2026-06-29.json",
    "WORKSPACE_SCAFFOLD/scripts/build_codex_hermes_a2a_queue_status.py",
    "data/pathspecs/sirinx_hermes_a2a_codex_sync_all_jobs_packet_2026-06-29.json",
    "docs/knowledge/SIRINX_HERMES_A2A_CODEX_SYNC_ALL_JOBS_PACKET_2026-06-29.md",
    "_A2A_QUEUE/inbox/packet_024_sirinx_hermes_a2a_codex_sync_all_jobs.json",
    "GHOSTCLAW/a2a-hermes-codex-bridge/command-intents.ts",
    "GHOSTCLAW/a2a-hermes-codex-bridge/command-intents.test.ts",
    "data/pathspecs/ghostclaw_lane1_hermes_model_choice_boundary_2026-06-29.json",
    "docs/knowledge/SIRINX_GHOSTCLAW_LANE1_HERMES_MODEL_CHOICE_BOUNDARY_2026-06-29.md",
    "data/pathspecs/ghostclaw_lane1_packet013_decision_draft_2026-06-29.json",
    "docs/knowledge/SIRINX_GHOSTCLAW_LANE1_PACKET013_DECISION_DRAFT_2026-06-29.md",
    "_A2A_QUEUE/outbox/packet_015_ghostclaw_lane1_hermes_decision_draft.json",
    "_A2A_QUEUE/outbox/packet_016_ghostclaw_lane1_hermes_decision_intake_handoff.json",
    "_A2A_QUEUE/outbox/packet_017_ghostclaw_lane1_hermes_decision_preflight_audit.json",
    "_A2A_QUEUE/outbox/packet_018_ghostclaw_lane1_opus_architecture_packet_gate.json",
    "WORKSPACE_SCAFFOLD/scripts/build_lane1_hermes_decision_draft.py",
    "WORKSPACE_SCAFFOLD/scripts/build_lane1_hermes_decision_preflight_audit.py",
    "data/pathspecs/ghostclaw_lane1_hermes_decision_preflight_audit_2026-06-29.json",
    "docs/knowledge/SIRINX_GHOSTCLAW_LANE1_HERMES_DECISION_PREFLIGHT_AUDIT_2026-06-29.md",
    "WORKSPACE_SCAFFOLD/scripts/validate_lane1_opus_architecture_packet.py",
    "data/pathspecs/ghostclaw_lane1_opus_architecture_packet_gate_2026-06-29.json",
    "docs/knowledge/SIRINX_GHOSTCLAW_LANE1_OPUS_ARCHITECTURE_PACKET_GATE_2026-06-29.md",
    "WORKSPACE_SCAFFOLD/tests/test_lane1_opus_architecture_packet_gate.py",
    "data/pathspecs/ghostclaw_lane1_opus_authoring_bundle_2026-06-29.json",
    "docs/knowledge/SIRINX_GHOSTCLAW_LANE1_OPUS_AUTHORING_BUNDLE_2026-06-29.md",
    "_A2A_QUEUE/outbox/packet_019_ghostclaw_lane1_opus_authoring_bundle.json",
    "WORKSPACE_SCAFFOLD/tests/test_lane1_opus_authoring_bundle.py",
    "data/pathspecs/sirinx_all_chat_export_request_packet_2026-06-29.json",
    "docs/knowledge/SIRINX_ALL_CHAT_EXPORT_REQUEST_PACKET_2026-06-29.md",
    "_A2A_QUEUE/outbox/packet_020_sirinx_all_chat_export_request.json",
    "WORKSPACE_SCAFFOLD/tests/test_all_chat_export_request_packet.py",
    "data/pathspecs/sirinx_a2a_adaptive_sync_control_status_2026-06-29.json",
    "docs/knowledge/SIRINX_A2A_ADAPTIVE_SYNC_CONTROL_STATUS_2026-06-29.md",
    "_A2A_QUEUE/outbox/packet_021_sirinx_a2a_adaptive_sync_control_status.json",
    "WORKSPACE_SCAFFOLD/tests/test_a2a_adaptive_sync_control_status_packet.py",
    "data/pathspecs/sirinx_a2a_next_safe_action_sequencer_2026-06-29.json",
    "docs/knowledge/SIRINX_A2A_NEXT_SAFE_ACTION_SEQUENCER_2026-06-29.md",
    "_A2A_QUEUE/outbox/packet_022_sirinx_a2a_next_safe_action_sequencer.json",
    "WORKSPACE_SCAFFOLD/tests/test_a2a_next_safe_action_sequencer_packet.py",
    "data/pathspecs/sirinx_hermes_gateway_current_recheck_packet_2026-06-29.json",
    "docs/knowledge/SIRINX_HERMES_GATEWAY_CURRENT_RECHECK_PACKET_2026-06-29.md",
    "_A2A_QUEUE/outbox/packet_023_sirinx_hermes_gateway_current_recheck.json",
    "WORKSPACE_SCAFFOLD/tests/test_hermes_gateway_current_recheck_packet.py",
    "data/pathspecs/ghostclaw_lane1_hermes_decision_transition_guard_2026-06-29.json",
    "docs/knowledge/SIRINX_GHOSTCLAW_LANE1_HERMES_DECISION_TRANSITION_GUARD_2026-06-29.md",
    "WORKSPACE_SCAFFOLD/scripts/build_lane1_hermes_decision_transition_guard.py",
    "data/pathspecs/ghostclaw_lane1_hermes_decision_intake_handoff_2026-06-29.json",
    "docs/knowledge/SIRINX_GHOSTCLAW_LANE1_HERMES_DECISION_INTAKE_HANDOFF_2026-06-29.md",
    "WORKSPACE_SCAFFOLD/scripts/build_lane1_hermes_decision_intake_handoff.py",
    "WORKSPACE_SCAFFOLD/manifests/active_goal_local_evidence_durability_2026-06-29.json",
    "docs/knowledge/SIRINX_ACTIVE_GOAL_LOCAL_EVIDENCE_DURABILITY_MANIFEST_2026-06-29.md",
    "WORKSPACE_SCAFFOLD/tests/test_active_goal_systematic_work_index.py",
  ],
  nextAction:
    "Review packet_023 as current gateway evidence; Hermes/operator verifies 127.0.0.1:9000 before live routing or packet_013 claims.",
};

export const GOD_MODE_CODEX_HERMES_EXECUTION_QUEUE: GodModeCodexHermesExecutionQueue = {
  status: "active_local_only",
  evidenceBoundary: "local_evidence_only",
  claimsAllChatsRead: false,
  lane2Authorized: false,
  runtimeQueueExecution: false,
  externalWrites: false,
  items: [
    {
      id: "LANE1-HERMES-DECISION-PACKET-013",
      priority: "P0",
      owner: "Hermes",
      status: "waiting_for_decision",
      gate: "codex_recorder_gate_closed",
      currentActionablePacket: "packet_013",
      lane2Authorized: false,
      nextAction:
        "Record a separate local Hermes decision: route_to_opus, request_revision, open_codex_recorder_gate, or block.",
      evidence: [
        "_A2A_QUEUE/inbox/packet_013_ghostclaw_lane1_codex_recorder_gate_request.json",
        "data/pathspecs/ghostclaw_lane1_hermes_decision_inbox_2026-06-29.json",
        "data/pathspecs/ghostclaw_lane1_packet013_decision_workbench_2026-06-29.json",
        "data/pathspecs/ghostclaw_lane1_packet013_decision_readiness_2026-06-29.json",
        "docs/knowledge/SIRINX_GHOSTCLAW_LANE1_PACKET013_DECISION_READINESS_2026-06-29.md",
        "data/pathspecs/ghostclaw_lane1_hermes_model_choice_boundary_2026-06-29.json",
        "docs/knowledge/SIRINX_GHOSTCLAW_LANE1_HERMES_MODEL_CHOICE_BOUNDARY_2026-06-29.md",
        "data/pathspecs/ghostclaw_lane1_hermes_decision_validator_2026-06-29.json",
        "data/pathspecs/sirinx_hermes_gateway_recheck_2026-06-29.json",
        "data/pathspecs/ghostclaw_lane1_hermes_decision_intake_handoff_2026-06-29.json",
        "docs/knowledge/SIRINX_GHOSTCLAW_LANE1_HERMES_DECISION_INTAKE_HANDOFF_2026-06-29.md",
        "WORKSPACE_SCAFFOLD/scripts/build_lane1_hermes_decision_intake_handoff.py",
      ],
      blockedBy: ["BLOCK-LANE1-OPUS-PACKET", "BLOCK-HERMES-GATEWAY"],
      allowedActions: ["read_local_files", "write_decision_draft", "run_local_tests", "update_status_docs"],
      forbiddenActions: [
        "deploy",
        "push",
        "secret_read",
        "paid_provider_call",
        "runtime_queue_execution",
        "cloud_mutation",
        "customer_send",
      ],
    },
    {
      id: "LANE1-HERMES-DECISION-DRAFT-PACKET-015",
      priority: "P0",
      owner: "Codex",
      status: "draft_for_hermes_review_not_decision",
      gate: "hermes_decision_required",
      currentActionablePacket: "packet_013",
      lane2Authorized: false,
      nextAction:
        "Review the draft-only route_to_opus decision aid; Hermes must still record a separate validated decision before any Codex recorder or LANE_2 action.",
      evidence: [
        "WORKSPACE_SCAFFOLD/scripts/build_lane1_hermes_decision_draft.py",
        "data/pathspecs/ghostclaw_lane1_packet013_decision_draft_2026-06-29.json",
        "docs/knowledge/SIRINX_GHOSTCLAW_LANE1_PACKET013_DECISION_DRAFT_2026-06-29.md",
        "_A2A_QUEUE/outbox/packet_015_ghostclaw_lane1_hermes_decision_draft.json",
        "WORKSPACE_SCAFFOLD/tests/test_lane1_packet013_decision_draft.py",
      ],
      blockedBy: ["BLOCK-LANE1-OPUS-PACKET", "BLOCK-HERMES-GATEWAY"],
      allowedActions: ["read_local_files", "review_decision_draft", "run_local_tests", "update_status_docs"],
      forbiddenActions: [
        "deploy",
        "push",
        "secret_read",
        "paid_provider_call",
        "provider_call",
        "runtime_queue_execution",
        "cloud_mutation",
        "customer_send",
        "telegram_live_send",
        "external_message_send",
        "merge_script_execution",
        "install",
        "migration",
        "decision_record",
      ],
    },
    {
      id: "LANE1-HERMES-DECISION-HANDOFF-PACKET-016",
      priority: "P0",
      owner: "Codex",
      status: "handoff_packet_ready_not_decision",
      gate: "hermes_decision_record_required",
      currentActionablePacket: "packet_013",
      lane2Authorized: false,
      nextAction:
        "Use packet_016 as the local outbox pointer to the decision intake handoff; Hermes still records a separate validated decision before any Codex recorder or LANE_2 action.",
      evidence: [
        "_A2A_QUEUE/outbox/packet_016_ghostclaw_lane1_hermes_decision_intake_handoff.json",
        "data/pathspecs/ghostclaw_lane1_hermes_decision_intake_handoff_2026-06-29.json",
        "docs/knowledge/SIRINX_GHOSTCLAW_LANE1_HERMES_DECISION_INTAKE_HANDOFF_2026-06-29.md",
        "WORKSPACE_SCAFFOLD/scripts/build_lane1_hermes_decision_intake_handoff.py",
        "WORKSPACE_SCAFFOLD/tests/test_lane1_hermes_decision_handoff_packet.py",
      ],
      blockedBy: ["BLOCK-LANE1-OPUS-PACKET", "BLOCK-HERMES-GATEWAY"],
      allowedActions: ["read_local_files", "review_handoff_packet", "run_local_tests", "update_status_docs"],
      forbiddenActions: [
        "deploy",
        "push",
        "secret_read",
        "paid_provider_call",
        "provider_call",
        "runtime_queue_execution",
        "cloud_mutation",
        "customer_send",
        "telegram_live_send",
        "external_message_send",
        "merge_script_execution",
        "install",
        "migration",
        "decision_record",
        "state_mutation",
      ],
    },
    {
      id: "LANE1-HERMES-DECISION-PREFLIGHT-PACKET-017",
      priority: "P0",
      owner: "Codex",
      status: "ready_for_hermes_decision_review_not_decision",
      gate: "hermes_decision_record_required",
      currentActionablePacket: "packet_013",
      lane2Authorized: false,
      nextAction:
        "Use packet_017 as the local preflight audit proving review evidence is ready; Hermes still records a separate validated decision before any state change.",
      evidence: [
        "WORKSPACE_SCAFFOLD/scripts/build_lane1_hermes_decision_preflight_audit.py",
        "data/pathspecs/ghostclaw_lane1_hermes_decision_preflight_audit_2026-06-29.json",
        "docs/knowledge/SIRINX_GHOSTCLAW_LANE1_HERMES_DECISION_PREFLIGHT_AUDIT_2026-06-29.md",
        "_A2A_QUEUE/outbox/packet_017_ghostclaw_lane1_hermes_decision_preflight_audit.json",
        "WORKSPACE_SCAFFOLD/tests/test_lane1_hermes_decision_preflight_audit.py",
      ],
      blockedBy: ["BLOCK-LANE1-OPUS-PACKET", "BLOCK-HERMES-GATEWAY"],
      allowedActions: ["read_local_files", "review_preflight_audit", "run_local_tests", "update_status_docs"],
      forbiddenActions: [
        "deploy",
        "push",
        "secret_read",
        "paid_provider_call",
        "provider_call",
        "runtime_queue_execution",
        "cloud_mutation",
        "customer_send",
        "telegram_live_send",
        "external_message_send",
        "merge_script_execution",
        "install",
        "migration",
        "decision_record",
        "state_mutation",
      ],
    },
    {
      id: "LANE1-OPUS-ARCHITECTURE-PACKET-GATE-PACKET-018",
      priority: "P0",
      owner: "Codex",
      status: "validator_ready_final_packet_missing",
      gate: "hermes_decision_and_final_packet_required",
      currentActionablePacket: "packet_013",
      lane2Authorized: false,
      nextAction:
        "Use packet_018 to validate a future final Opus architecture packet; do not create the final packet until Hermes/Opus decision evidence exists.",
      evidence: [
        "WORKSPACE_SCAFFOLD/scripts/validate_lane1_opus_architecture_packet.py",
        "data/pathspecs/ghostclaw_lane1_opus_architecture_packet_gate_2026-06-29.json",
        "docs/knowledge/SIRINX_GHOSTCLAW_LANE1_OPUS_ARCHITECTURE_PACKET_GATE_2026-06-29.md",
        "_A2A_QUEUE/outbox/packet_018_ghostclaw_lane1_opus_architecture_packet_gate.json",
        "WORKSPACE_SCAFFOLD/tests/test_lane1_opus_architecture_packet_gate.py",
      ],
      blockedBy: ["BLOCK-LANE1-OPUS-PACKET", "BLOCK-HERMES-GATEWAY"],
      allowedActions: ["read_local_files", "validate_future_final_packet", "run_local_tests", "update_status_docs"],
      forbiddenActions: [
        "deploy",
        "push",
        "secret_read",
        "paid_provider_call",
        "provider_call",
        "runtime_queue_execution",
        "cloud_mutation",
        "customer_send",
        "telegram_live_send",
        "external_message_send",
        "merge_script_execution",
        "install",
        "migration",
        "decision_record",
        "state_mutation",
        "final_packet_creation",
        "lane2_authorization",
      ],
    },
    {
      id: "LANE1-OPUS-AUTHORING-BUNDLE-PACKET-019",
      priority: "P0",
      owner: "Codex",
      status: "authoring_bundle_ready_not_final_packet",
      gate: "hermes_decision_and_final_packet_required",
      currentActionablePacket: "packet_013",
      lane2Authorized: false,
      nextAction:
        "Use packet_019 as local evidence for Hermes/Opus authoring only; it is not the final packet and cannot open LANE_2.",
      evidence: [
        "data/pathspecs/ghostclaw_lane1_opus_authoring_bundle_2026-06-29.json",
        "docs/knowledge/SIRINX_GHOSTCLAW_LANE1_OPUS_AUTHORING_BUNDLE_2026-06-29.md",
        "_A2A_QUEUE/outbox/packet_019_ghostclaw_lane1_opus_authoring_bundle.json",
        "WORKSPACE_SCAFFOLD/tests/test_lane1_opus_authoring_bundle.py",
      ],
      blockedBy: ["BLOCK-LANE1-OPUS-PACKET", "BLOCK-HERMES-GATEWAY"],
      allowedActions: ["read_local_files", "draft_architecture_packet_candidate", "run_local_tests", "update_status_docs"],
      forbiddenActions: [
        "deploy",
        "push",
        "secret_read",
        "paid_provider_call",
        "provider_call",
        "runtime_queue_execution",
        "cloud_mutation",
        "customer_send",
        "telegram_live_send",
        "external_message_send",
        "merge_script_execution",
        "install",
        "migration",
        "decision_record",
        "state_mutation",
        "final_packet_creation",
        "lane2_authorization",
      ],
    },
    {
      id: "LANE1-HERMES-DECISION-TRANSITION-GUARD",
      priority: "P0",
      owner: "Codex",
      status: "blocked_missing_hermes_decision",
      gate: "validated_hermes_decision_required",
      currentActionablePacket: "packet_013",
      lane2Authorized: false,
      nextAction:
        "Run the transition guard after Hermes records a separate validated decision; do not mutate queue state from a draft.",
      evidence: [
        "WORKSPACE_SCAFFOLD/scripts/build_lane1_hermes_decision_transition_guard.py",
        "data/pathspecs/ghostclaw_lane1_hermes_decision_transition_guard_2026-06-29.json",
        "docs/knowledge/SIRINX_GHOSTCLAW_LANE1_HERMES_DECISION_TRANSITION_GUARD_2026-06-29.md",
        "WORKSPACE_SCAFFOLD/tests/test_lane1_hermes_decision_transition_guard.py",
      ],
      blockedBy: ["BLOCK-LANE1-OPUS-PACKET", "BLOCK-HERMES-GATEWAY"],
      allowedActions: ["read_local_files", "validate_decision_transition", "run_local_tests", "update_status_docs"],
      forbiddenActions: [
        "deploy",
        "push",
        "secret_read",
        "paid_provider_call",
        "provider_call",
        "runtime_queue_execution",
        "cloud_mutation",
        "customer_send",
        "telegram_live_send",
        "external_message_send",
        "merge_script_execution",
        "install",
        "migration",
        "decision_record",
        "state_mutation",
      ],
    },
    {
      id: "ALL-CHAT-EXPORT-INTAKE",
      priority: "P0",
      owner: "Operator",
      status: "request_packet_ready_export_missing",
      gate: "chat_export_required",
      nextAction: "Review packet_020 request, then provide a ChatGPT export or connector-backed source before claiming all chats were read.",
      evidence: [
        "docs/knowledge/SIRINX_ACTIVE_GOAL_COMPLETION_AUDIT_2026-06-29.md",
        "data/pathspecs/sirinx_active_goal_systematic_work_index_2026-06-29.json",
        "data/pathspecs/sirinx_all_chat_export_intake_contract_2026-06-29.json",
        "data/pathspecs/sirinx_all_chat_export_intake_mapper_2026-06-29.json",
        "docs/knowledge/SIRINX_ALL_CHAT_EXPORT_INTAKE_MAPPER_2026-06-29.md",
        "data/pathspecs/sirinx_all_chat_export_request_packet_2026-06-29.json",
        "docs/knowledge/SIRINX_ALL_CHAT_EXPORT_REQUEST_PACKET_2026-06-29.md",
        "_A2A_QUEUE/outbox/packet_020_sirinx_all_chat_export_request.json",
      ],
      blockedBy: ["BLOCK-CHAT-EXPORT"],
      allowedActions: ["read_local_files", "prepare_import_schema", "run_metadata_only_mapper", "update_status_docs"],
      forbiddenActions: [
        "deploy",
        "push",
        "secret_read",
        "paid_provider_call",
        "runtime_queue_execution",
        "cloud_mutation",
        "customer_send",
      ],
    },
    {
      id: "ALL-CHAT-EXPORT-REQUEST-PACKET-020",
      priority: "P0",
      owner: "Codex",
      status: "request_packet_ready_no_export_loaded",
      gate: "chat_export_required",
      nextAction:
        "Use packet_020 to request an operator-supplied ChatGPT export path or explicitly authorized read-only connector scope; do not claim all chats were read until metadata mapping is reviewed.",
      evidence: [
        "data/pathspecs/sirinx_all_chat_export_request_packet_2026-06-29.json",
        "docs/knowledge/SIRINX_ALL_CHAT_EXPORT_REQUEST_PACKET_2026-06-29.md",
        "_A2A_QUEUE/outbox/packet_020_sirinx_all_chat_export_request.json",
        "data/pathspecs/sirinx_all_chat_export_intake_contract_2026-06-29.json",
        "data/pathspecs/sirinx_all_chat_export_intake_mapper_2026-06-29.json",
        "WORKSPACE_SCAFFOLD/tests/test_all_chat_export_request_packet.py",
      ],
      blockedBy: ["BLOCK-CHAT-EXPORT"],
      allowedActions: [
        "read_local_files",
        "request_operator_supplied_source",
        "record_source_receipt_metadata",
        "run_metadata_only_mapper_after_source_exists",
        "update_status_docs",
      ],
      forbiddenActions: [
        "deploy",
        "push",
        "secret_read",
        "paid_provider_call",
        "provider_call",
        "runtime_queue_execution",
        "cloud_mutation",
        "customer_send",
        "telegram_live_send",
        "external_message_send",
        "merge_script_execution",
        "install",
        "migration",
        "raw_chat_content_stored",
        "claims_all_chats_read",
        "connector_read_performed",
        "external_upload",
      ],
    },
    {
      id: "A2A-ADAPTIVE-SYNC-CONTROL-STATUS-PACKET-021",
      priority: "P0",
      owner: "Codex",
      status: "a2a_adaptive_sync_control_status_ready_local_only",
      gate: "local_read_only_status_review",
      nextAction:
        "Review packet_021 as the current local A2A adaptive sync control status, then choose one separate gated blocker-clearing lane.",
      evidence: [
        "data/pathspecs/sirinx_a2a_adaptive_sync_control_status_2026-06-29.json",
        "docs/knowledge/SIRINX_A2A_ADAPTIVE_SYNC_CONTROL_STATUS_2026-06-29.md",
        "_A2A_QUEUE/outbox/packet_021_sirinx_a2a_adaptive_sync_control_status.json",
        "data/pathspecs/sirinx_codex_hermes_a2a_queue_status_2026-06-29.json",
        "WORKSPACE_SCAFFOLD/tests/test_a2a_adaptive_sync_control_status_packet.py",
      ],
      blockedBy: [
        "BLOCK-CHAT-EXPORT",
        "BLOCK-LANE1-OPUS-PACKET",
        "BLOCK-HERMES-GATEWAY",
        "BLOCK-V3-3-ARTIFACT",
        "BLOCK-R0-APPROVALS",
      ],
      allowedActions: ["read_local_files", "review_status_packet", "run_local_tests", "update_status_docs"],
      forbiddenActions: [
        "deploy",
        "push",
        "secret_read",
        "paid_provider_call",
        "provider_call",
        "runtime_queue_execution",
        "cloud_mutation",
        "customer_send",
        "telegram_live_send",
        "external_message_send",
        "merge_script_execution",
        "install",
        "migration",
        "connector_read",
        "claims_all_chats_read",
        "lane2_authorization",
        "state_mutation",
      ],
    },
    {
      id: "A2A-NEXT-SAFE-ACTION-SEQUENCER-PACKET-022",
      priority: "P0",
      owner: "Codex",
      status: "a2a_next_safe_action_sequencer_ready_local_only",
      gate: "local_read_only_next_lane_review",
      nextAction:
        "Review packet_022 as a deterministic local sequencer; Hermes still records a separate packet_013 decision before any recorder-gate, final-packet, or LANE_2 state change.",
      evidence: [
        "data/pathspecs/sirinx_a2a_next_safe_action_sequencer_2026-06-29.json",
        "docs/knowledge/SIRINX_A2A_NEXT_SAFE_ACTION_SEQUENCER_2026-06-29.md",
        "_A2A_QUEUE/outbox/packet_022_sirinx_a2a_next_safe_action_sequencer.json",
        "data/pathspecs/sirinx_a2a_adaptive_sync_control_status_2026-06-29.json",
        "_A2A_QUEUE/outbox/packet_021_sirinx_a2a_adaptive_sync_control_status.json",
        "WORKSPACE_SCAFFOLD/tests/test_a2a_next_safe_action_sequencer_packet.py",
      ],
      blockedBy: [
        "BLOCK-CHAT-EXPORT",
        "BLOCK-LANE1-OPUS-PACKET",
        "BLOCK-HERMES-GATEWAY",
        "BLOCK-V3-3-ARTIFACT",
        "BLOCK-R0-APPROVALS",
      ],
      allowedActions: [
        "read_local_files",
        "review_next_safe_action_sequence",
        "run_local_tests",
        "update_status_docs",
      ],
      forbiddenActions: [
        "deploy",
        "push",
        "secret_read",
        "paid_provider_call",
        "provider_call",
        "runtime_queue_execution",
        "cloud_mutation",
        "customer_send",
        "telegram_live_send",
        "external_message_send",
        "connector_read",
        "decision_record",
        "state_mutation",
        "lane2_authorization",
        "merge_script_execution",
        "install",
        "migration",
        "claims_all_chats_read",
        "completion_claim",
      ],
    },
    {
      id: "GHOSTCLAW-V3-3-ARTIFACT-INTAKE",
      priority: "P1",
      owner: "Codex",
      status: "blocked_exact_artifact_missing",
      gate: "exact_artifact_required",
      nextAction: "Re-run metadata-only artifact intake after the exact v3.3 merge kit path exists.",
      evidence: [
        "docs/knowledge/SIRINX_GHOSTCLAW_V3_3_MERGE_INTAKE_2026-06-29.md",
        "docs/knowledge/SIRINX_GHOSTCLAW_V3_3_PREFLIGHT_RECHECK_2026-06-29.md",
        "data/pathspecs/sirinx_ghostclaw_v3_3_artifact_gate_validator_2026-06-29.json",
        "docs/knowledge/SIRINX_GHOSTCLAW_V3_3_ARTIFACT_GATE_VALIDATOR_2026-06-29.md",
        "data/pathspecs/sirinx_hermes_codex_a2a_godmode_v3_html_recheck_2026-06-29.json",
      ],
      blockedBy: ["BLOCK-V3-3-ARTIFACT"],
      allowedActions: ["read_local_files", "metadata_only_artifact_inventory", "update_status_docs"],
      forbiddenActions: [
        "deploy",
        "push",
        "secret_read",
        "paid_provider_call",
        "runtime_queue_execution",
        "cloud_mutation",
        "customer_send",
        "merge_script_execution",
      ],
    },
    {
      id: "R0-GATE-SPECIFIC-APPROVALS",
      priority: "P1",
      owner: "Operator",
      status: "blocked_approval_missing",
      gate: "r0_gate_specific_approval_required",
      nextAction: "Approve one named R0 gate with target, environment, rollback, and evidence path.",
      evidence: [
        "PROJECT_STATE.md",
        "NEXT_ACTIONS.md",
        "data/pathspecs/sirinx_r0_gate_specific_approval_contract_2026-06-29.json",
        "apps/pocket-hatchery/ops/release_gate_evidence.md",
      ],
      blockedBy: ["BLOCK-R0-APPROVALS"],
      allowedActions: ["read_local_files", "update_status_docs", "run_local_tests"],
      forbiddenActions: [
        "deploy",
        "push",
        "secret_read",
        "paid_provider_call",
        "runtime_queue_execution",
        "cloud_mutation",
        "customer_send",
        "testnet_deploy",
        "wallet_transaction",
      ],
    },
    {
      id: "ACTIVE-GOAL-BLOCKER-RECHECK",
      priority: "P2",
      owner: "Codex",
      status: "done_current_state",
      gate: "local_read_only_probe_only",
      nextAction: "Use current blocker proof before claiming completion or choosing the next safe lane.",
      evidence: [
        "data/pathspecs/sirinx_active_goal_blocker_recheck_2026-06-29.json",
        "data/pathspecs/sirinx_active_goal_blocker_clearance_validator_2026-06-29.json",
        "data/pathspecs/sirinx_active_goal_current_blocker_refresh_2026-06-29.json",
        "WORKSPACE_SCAFFOLD/scripts/probe_active_goal_blockers.py",
        "data/pathspecs/sirinx_active_goal_read_only_probe_runner_2026-06-29.json",
        "docs/knowledge/SIRINX_ACTIVE_GOAL_READ_ONLY_PROBE_RUNNER_2026-06-29.md",
        "WORKSPACE_SCAFFOLD/reports/active_goal_read_only_probe_latest_2026-06-29.json",
        "docs/knowledge/SIRINX_ACTIVE_GOAL_BLOCKER_RECHECK_2026-06-29.md",
        "docs/knowledge/SIRINX_ACTIVE_GOAL_BLOCKER_CLEARANCE_VALIDATOR_2026-06-29.md",
      ],
      blockedBy: [
        "BLOCK-CHAT-EXPORT",
        "BLOCK-LANE1-OPUS-PACKET",
        "BLOCK-HERMES-GATEWAY",
        "BLOCK-V3-3-ARTIFACT",
        "BLOCK-R0-APPROVALS",
      ],
      allowedActions: ["read_local_files", "run_local_tests", "run_read_only_blocker_probe", "update_status_docs"],
      forbiddenActions: [
        "deploy",
        "push",
        "secret_read",
        "paid_provider_call",
        "runtime_queue_execution",
        "cloud_mutation",
        "customer_send",
        "merge_script_execution",
        "install",
        "migration",
      ],
    },
    {
      id: "HERMES-GATEWAY-CURRENT-RECHECK-PACKET-023",
      priority: "P0",
      owner: "Codex",
      status: "hermes_gateway_current_recheck_ready_local_only",
      gate: "local_read_only_gateway_status_review",
      nextAction:
        "Review packet_023 as current localhost gateway evidence; Hermes or the operator must start or verify the gateway separately before any live routing or packet_013 decision claim.",
      evidence: [
        "data/pathspecs/sirinx_hermes_gateway_current_recheck_packet_2026-06-29.json",
        "docs/knowledge/SIRINX_HERMES_GATEWAY_CURRENT_RECHECK_PACKET_2026-06-29.md",
        "_A2A_QUEUE/outbox/packet_023_sirinx_hermes_gateway_current_recheck.json",
        "data/pathspecs/sirinx_hermes_gateway_recheck_2026-06-29.json",
        "WORKSPACE_SCAFFOLD/tests/test_hermes_gateway_current_recheck_packet.py",
      ],
      blockedBy: ["BLOCK-HERMES-GATEWAY"],
      allowedActions: [
        "read_local_files",
        "run_local_tests",
        "update_status_docs",
        "rerun_read_only_gateway_probe",
      ],
      forbiddenActions: [
        "deploy",
        "push",
        "secret_read",
        "paid_provider_call",
        "provider_call",
        "runtime_queue_execution",
        "cloud_mutation",
        "customer_send",
        "telegram_live_send",
        "external_message_send",
        "merge_script_execution",
        "install",
        "migration",
        "restart_hermes",
        "decision_record",
        "state_mutation",
        "lane2_authorization",
      ],
    },
    {
      id: "HERMES-A2A-CODEX-SYNC-ALL-JOBS-PACKET-024",
      priority: "P0",
      owner: "Hermes / Codex",
      status: "goal_command_inbox_ready_local_only",
      gate: "local_read_only_goal_command_review",
      nextAction:
        "Review packet_024 as a local /goal command for Hermes A2A Codex sync-all-jobs coordination; do not execute Codex CLI, runtime queues, provider calls, external sends, or license changes.",
      evidence: [
        "data/pathspecs/sirinx_hermes_a2a_codex_sync_all_jobs_packet_2026-06-29.json",
        "docs/knowledge/SIRINX_HERMES_A2A_CODEX_SYNC_ALL_JOBS_PACKET_2026-06-29.md",
        "_A2A_QUEUE/inbox/packet_024_sirinx_hermes_a2a_codex_sync_all_jobs.json",
        "GHOSTCLAW/a2a-hermes-codex-bridge/command-intents.ts",
        "GHOSTCLAW/a2a-hermes-codex-bridge/command-intents.test.ts",
        "docs/superpowers/decisions/2026-06-29-a2a-sync-hermes-goal-mission-brainstorm.md",
      ],
      blockedBy: [
        "packet_013_decision_still_current_actionable",
        "license_file_absent",
        "runtime_queue_execution_not_approved",
      ],
      allowedActions: ["read_local_files", "review_goal_command_packet", "run_local_tests", "update_status_docs"],
      forbiddenActions: [
        "deploy",
        "push",
        "secret_read",
        "paid_provider_call",
        "provider_call",
        "runtime_queue_execution",
        "real_codex_cli_execution",
        "cloud_mutation",
        "customer_send",
        "telegram_live_send",
        "external_message_send",
        "merge_script_execution",
        "install",
        "migration",
        "state_mutation",
        "lane2_authorization",
        "license_file_creation_without_approval",
        "license_claim_without_license_file",
      ],
    },
    {
      id: "BROWSER-USE-CANDIDATE-LANE-PACKET-025",
      priority: "P1",
      owner: "Codex",
      status: "browser_use_candidate_lane_ready_local_only",
      gate: "candidate_review_only_install_gate_required",
      nextAction:
        "Review Browser Use as candidate browser QA evidence only; request a gate-specific approval before installing it or opening any page through it.",
      evidence: [
        "data/pathspecs/sirinx_browser_use_candidate_lane_2026-06-29.json",
        "docs/knowledge/SIRINX_BROWSER_USE_CANDIDATE_LANE_2026-06-29.md",
        "_A2A_QUEUE/outbox/packet_025_sirinx_browser_use_candidate_lane.json",
        "WORKSPACE_SCAFFOLD/tests/test_browser_use_candidate_lane.py",
      ],
      blockedBy: [
        "browser_use_install_not_approved",
        "browser_use_execution_not_approved",
        "browser_use_cloud_not_approved",
        "real_profile_or_cookie_access_not_approved",
      ],
      allowedActions: [
        "read_public_metadata",
        "review_candidate_lane",
        "run_local_tests",
        "update_status_docs",
      ],
      forbiddenActions: [
        "deploy",
        "push",
        "secret_read",
        "paid_provider_call",
        "provider_call",
        "runtime_queue_execution",
        "browser_execution",
        "install_browser_use",
        "install",
        "migration",
        "browser_use_cloud",
        "profile_sync",
        "cookie_export",
        "cookie_import",
        "real_chrome_profile",
        "form_submit",
        "transaction_confirm",
        "tunnel",
        "captcha_bypass",
        "cloud_mutation",
        "customer_send",
        "telegram_live_send",
        "external_message_send",
        "merge_script_execution",
        "state_mutation",
      ],
    },
    {
      id: "MISSION-CONTROL-READONLY-EVIDENCE",
      priority: "P2",
      owner: "Codex",
      status: "done_local_readonly",
      gate: "no_runtime_gate_unlock",
      nextAction: "Keep panels sourced from static local evidence unless a runtime integration gate is approved.",
      evidence: [
        "apps/centerbrain-shell/src/lib/god-mode-master-os.ts",
        "apps/centerbrain-shell/app/ui/GodModeMasterOS.tsx",
      ],
      blockedBy: ["runtime_file_access_not_approved", "runtime_queue_execution_not_approved"],
      allowedActions: ["read_local_files", "run_local_tests", "update_static_ui_data", "update_status_docs"],
      forbiddenActions: [
        "deploy",
        "push",
        "secret_read",
        "paid_provider_call",
        "runtime_queue_execution",
        "cloud_mutation",
        "customer_send",
      ],
    },
    {
      id: "CODEX-HERMES-A2A-QUEUE-STATUS",
      priority: "P2",
      owner: "Codex",
      status: "local_queue_indexed_not_executed",
      gate: "local_file_bus_only",
      nextAction: "Use the A2A file-bus status snapshot for local Codex/Hermes coordination; do not execute queue items.",
      evidence: [
        "data/pathspecs/sirinx_codex_hermes_a2a_queue_status_2026-06-29.json",
        "docs/knowledge/SIRINX_CODEX_HERMES_A2A_QUEUE_STATUS_2026-06-29.md",
        "WORKSPACE_SCAFFOLD/reports/codex_hermes_a2a_queue_status_latest_2026-06-29.json",
        "WORKSPACE_SCAFFOLD/scripts/build_codex_hermes_a2a_queue_status.py",
        "WORKSPACE_SCAFFOLD/tests/test_codex_hermes_a2a_queue_status.py",
      ],
      blockedBy: ["BLOCK-LANE1-OPUS-PACKET", "BLOCK-HERMES-GATEWAY"],
      allowedActions: ["read_local_files", "index_local_queue", "run_local_tests", "update_status_docs"],
      forbiddenActions: [
        "deploy",
        "push",
        "secret_read",
        "paid_provider_call",
        "runtime_queue_execution",
        "cloud_mutation",
        "customer_send",
        "telegram_live_send",
        "external_message_send",
        "merge_script_execution",
        "install",
        "migration",
      ],
    },
    {
      id: "COMPLETION-REQUIREMENTS-MATRIX",
      priority: "P2",
      owner: "Codex",
      status: "requirements_mapped_not_complete",
      gate: "no_completion_claim_without_requirement_proof",
      nextAction: "Use requirement-level evidence before any active-goal completion claim.",
      evidence: [
        "data/pathspecs/sirinx_active_goal_completion_requirements_matrix_2026-06-29.json",
        "docs/knowledge/SIRINX_ACTIVE_GOAL_COMPLETION_REQUIREMENTS_MATRIX_2026-06-29.md",
        "WORKSPACE_SCAFFOLD/tests/test_active_goal_completion_requirements_matrix.py",
      ],
      blockedBy: [
        "BLOCK-CHAT-EXPORT",
        "BLOCK-LANE1-OPUS-PACKET",
        "BLOCK-HERMES-GATEWAY",
        "BLOCK-V3-3-ARTIFACT",
        "BLOCK-R0-APPROVALS",
      ],
      allowedActions: ["read_local_files", "map_requirements", "run_local_tests", "update_status_docs"],
      forbiddenActions: [
        "deploy",
        "push",
        "secret_read",
        "paid_provider_call",
        "runtime_queue_execution",
        "cloud_mutation",
        "customer_send",
        "merge_script_execution",
        "install",
        "migration",
        "completion_claim",
      ],
    },
    {
      id: "SOURCE-FILE-RECEIPT",
      priority: "P2",
      owner: "Codex",
      status: "current_local_scan_partial",
      gate: "local_file_evidence_only",
      nextAction:
        "Use the source-file receipt to separate current local files from user-message summaries before any all-files-read claim.",
      evidence: [
        "data/pathspecs/sirinx_active_goal_source_file_receipt_2026-06-29.json",
        "docs/knowledge/SIRINX_ACTIVE_GOAL_SOURCE_FILE_RECEIPT_2026-06-29.md",
        "WORKSPACE_SCAFFOLD/tests/test_active_goal_source_file_receipt.py",
      ],
      blockedBy: ["BLOCK-CHAT-EXPORT", "BLOCK-V3-3-ARTIFACT"],
      allowedActions: ["read_local_files", "metadata_only_file_scan", "run_local_tests", "update_status_docs"],
      forbiddenActions: [
        "deploy",
        "push",
        "secret_read",
        "paid_provider_call",
        "runtime_queue_execution",
        "cloud_mutation",
        "customer_send",
        "merge_script_execution",
        "install",
        "migration",
      ],
    },
    {
      id: "CODEX-HERMES-WORK-REPORT-DRAFT",
      priority: "P2",
      owner: "Codex",
      status: "telegram_draft_ready",
      gate: "telegram_live_send_gate_closed",
      nextAction:
        "Use the local Telegram-safe work report draft for operator review; live Telegram delivery requires APPROVE_TELEGRAM_WORK_REPORT_SEND.",
      evidence: [
        "data/pathspecs/sirinx_codex_hermes_work_report_contract_2026-06-29.json",
        "docs/knowledge/SIRINX_CODEX_HERMES_WORK_REPORT_DRAFT_2026-06-29.md",
        "_A2A_QUEUE/outbox/packet_014_codex_hermes_work_report_draft.json",
        "docs/knowledge/SIRINX_CODEX_HERMES_WORK_REPORT_PACKET_2026-06-29.md",
        "WORKSPACE_SCAFFOLD/scripts/build_codex_hermes_work_report.py",
        "WORKSPACE_SCAFFOLD/tests/test_codex_hermes_work_report.py",
        "WORKSPACE_SCAFFOLD/tests/test_codex_hermes_work_report_packet.py",
      ],
      blockedBy: ["telegram_live_send_gate_closed", "BLOCK-LANE1-OPUS-PACKET", "BLOCK-HERMES-GATEWAY"],
      allowedActions: ["read_local_files", "build_telegram_safe_report_draft", "run_local_tests", "update_status_docs"],
      forbiddenActions: [
        "deploy",
        "push",
        "secret_read",
        "paid_provider_call",
        "runtime_queue_execution",
        "cloud_mutation",
        "customer_send",
        "telegram_live_send",
        "external_message_send",
      ],
    },
    {
      id: "OBSIDIAN-BRAIN-SYNC-PULSE",
      priority: "P3",
      owner: "Codex",
      status: "active_after_meaningful_work",
      gate: "no_secrets_no_raw_logs",
      nextAction: "Append concise memory pulses after verified local work.",
      evidence: [
        "/Users/sirinx/Documents/Obsidian Vault/SIRINX/AI HQ Knowledge Digest.md",
        "/Users/sirinx/SIRINXDev/.ghostclaw_runtime/a2async/memory/obsidian_sync.jsonl",
      ],
      blockedBy: ["secret_or_raw_log_content"],
      allowedActions: ["read_local_files", "append_concise_digest_pulse", "write_local_sync_receipt"],
      forbiddenActions: [
        "deploy",
        "push",
        "secret_read",
        "paid_provider_call",
        "runtime_queue_execution",
        "cloud_mutation",
        "customer_send",
        "raw_log_dump",
      ],
    },
    {
      id: "LOCAL-EVIDENCE-DURABILITY",
      priority: "P3",
      owner: "Codex",
      status: "done_local_manifest",
      gate: "no_force_add_ignored_data",
      nextAction: "Use the manifest and docs mirror as the review surface for ignored data/pathspecs artifacts.",
      evidence: [
        "WORKSPACE_SCAFFOLD/manifests/active_goal_local_evidence_durability_2026-06-29.json",
        "docs/knowledge/SIRINX_ACTIVE_GOAL_LOCAL_EVIDENCE_DURABILITY_MANIFEST_2026-06-29.md",
        "WORKSPACE_SCAFFOLD/tests/test_active_goal_local_evidence_durability_manifest.py",
      ],
      blockedBy: ["data_pathspecs_ignored_by_gitignore"],
      allowedActions: ["read_local_files", "update_status_docs", "run_local_tests"],
      forbiddenActions: [
        "deploy",
        "push",
        "secret_read",
        "paid_provider_call",
        "runtime_queue_execution",
        "cloud_mutation",
        "customer_send",
        "force_add_ignored_data",
      ],
    },
  ],
  evidenceFiles: [
    "data/pathspecs/sirinx_codex_hermes_execution_queue_2026-06-29.json",
    "docs/knowledge/SIRINX_CODEX_HERMES_EXECUTION_QUEUE_2026-06-29.md",
    "docs/knowledge/SIRINX_HERMES_CODEX_A2A_GODMODE_V3_HTML_RECHECK_2026-06-29.md",
    "data/pathspecs/sirinx_active_goal_blocker_recheck_2026-06-29.json",
    "data/pathspecs/sirinx_active_goal_blocker_clearance_validator_2026-06-29.json",
    "data/pathspecs/sirinx_active_goal_current_blocker_refresh_2026-06-29.json",
    "WORKSPACE_SCAFFOLD/scripts/probe_active_goal_blockers.py",
    "data/pathspecs/sirinx_active_goal_read_only_probe_runner_2026-06-29.json",
    "docs/knowledge/SIRINX_ACTIVE_GOAL_READ_ONLY_PROBE_RUNNER_2026-06-29.md",
    "WORKSPACE_SCAFFOLD/reports/active_goal_read_only_probe_latest_2026-06-29.json",
    "data/pathspecs/sirinx_active_goal_completion_requirements_matrix_2026-06-29.json",
    "docs/knowledge/SIRINX_ACTIVE_GOAL_COMPLETION_REQUIREMENTS_MATRIX_2026-06-29.md",
    "data/pathspecs/sirinx_active_goal_context_packet_registry_2026-06-29.json",
    "data/pathspecs/sirinx_active_goal_source_file_receipt_2026-06-29.json",
    "docs/knowledge/SIRINX_ACTIVE_GOAL_SOURCE_FILE_RECEIPT_2026-06-29.md",
    "data/pathspecs/sirinx_codex_hermes_a2a_queue_status_2026-06-29.json",
    "docs/knowledge/SIRINX_CODEX_HERMES_A2A_QUEUE_STATUS_2026-06-29.md",
    "WORKSPACE_SCAFFOLD/reports/codex_hermes_a2a_queue_status_latest_2026-06-29.json",
    "WORKSPACE_SCAFFOLD/scripts/build_codex_hermes_a2a_queue_status.py",
    "data/pathspecs/sirinx_ghostclaw_v3_3_artifact_gate_validator_2026-06-29.json",
    "data/pathspecs/ghostclaw_lane1_packet013_decision_workbench_2026-06-29.json",
    "data/pathspecs/ghostclaw_lane1_packet013_decision_readiness_2026-06-29.json",
    "docs/knowledge/SIRINX_GHOSTCLAW_LANE1_PACKET013_DECISION_READINESS_2026-06-29.md",
    "data/pathspecs/ghostclaw_lane1_hermes_model_choice_boundary_2026-06-29.json",
    "docs/knowledge/SIRINX_GHOSTCLAW_LANE1_HERMES_MODEL_CHOICE_BOUNDARY_2026-06-29.md",
    "data/pathspecs/ghostclaw_lane1_hermes_decision_validator_2026-06-29.json",
    "data/pathspecs/ghostclaw_lane1_packet013_decision_draft_2026-06-29.json",
    "docs/knowledge/SIRINX_GHOSTCLAW_LANE1_PACKET013_DECISION_DRAFT_2026-06-29.md",
    "_A2A_QUEUE/outbox/packet_015_ghostclaw_lane1_hermes_decision_draft.json",
    "_A2A_QUEUE/outbox/packet_016_ghostclaw_lane1_hermes_decision_intake_handoff.json",
        "_A2A_QUEUE/outbox/packet_017_ghostclaw_lane1_hermes_decision_preflight_audit.json",
        "_A2A_QUEUE/outbox/packet_018_ghostclaw_lane1_opus_architecture_packet_gate.json",
        "_A2A_QUEUE/outbox/packet_019_ghostclaw_lane1_opus_authoring_bundle.json",
        "_A2A_QUEUE/outbox/packet_020_sirinx_all_chat_export_request.json",
        "_A2A_QUEUE/outbox/packet_021_sirinx_a2a_adaptive_sync_control_status.json",
        "data/pathspecs/sirinx_a2a_adaptive_sync_control_status_2026-06-29.json",
        "docs/knowledge/SIRINX_A2A_ADAPTIVE_SYNC_CONTROL_STATUS_2026-06-29.md",
        "WORKSPACE_SCAFFOLD/tests/test_a2a_adaptive_sync_control_status_packet.py",
        "_A2A_QUEUE/outbox/packet_022_sirinx_a2a_next_safe_action_sequencer.json",
        "data/pathspecs/sirinx_a2a_next_safe_action_sequencer_2026-06-29.json",
        "docs/knowledge/SIRINX_A2A_NEXT_SAFE_ACTION_SEQUENCER_2026-06-29.md",
        "WORKSPACE_SCAFFOLD/tests/test_a2a_next_safe_action_sequencer_packet.py",
        "_A2A_QUEUE/outbox/packet_023_sirinx_hermes_gateway_current_recheck.json",
        "data/pathspecs/sirinx_hermes_gateway_current_recheck_packet_2026-06-29.json",
        "docs/knowledge/SIRINX_HERMES_GATEWAY_CURRENT_RECHECK_PACKET_2026-06-29.md",
        "WORKSPACE_SCAFFOLD/tests/test_hermes_gateway_current_recheck_packet.py",
        "_A2A_QUEUE/inbox/packet_024_sirinx_hermes_a2a_codex_sync_all_jobs.json",
        "data/pathspecs/sirinx_hermes_a2a_codex_sync_all_jobs_packet_2026-06-29.json",
        "docs/knowledge/SIRINX_HERMES_A2A_CODEX_SYNC_ALL_JOBS_PACKET_2026-06-29.md",
        "GHOSTCLAW/a2a-hermes-codex-bridge/command-intents.ts",
        "GHOSTCLAW/a2a-hermes-codex-bridge/command-intents.test.ts",
        "_A2A_QUEUE/outbox/packet_025_sirinx_browser_use_candidate_lane.json",
        "data/pathspecs/sirinx_browser_use_candidate_lane_2026-06-29.json",
        "docs/knowledge/SIRINX_BROWSER_USE_CANDIDATE_LANE_2026-06-29.md",
        "WORKSPACE_SCAFFOLD/tests/test_browser_use_candidate_lane.py",
        "WORKSPACE_SCAFFOLD/scripts/build_lane1_hermes_decision_draft.py",
    "WORKSPACE_SCAFFOLD/scripts/build_lane1_hermes_decision_preflight_audit.py",
    "WORKSPACE_SCAFFOLD/tests/test_lane1_hermes_decision_preflight_audit.py",
    "data/pathspecs/ghostclaw_lane1_hermes_decision_preflight_audit_2026-06-29.json",
    "docs/knowledge/SIRINX_GHOSTCLAW_LANE1_HERMES_DECISION_PREFLIGHT_AUDIT_2026-06-29.md",
        "WORKSPACE_SCAFFOLD/scripts/validate_lane1_opus_architecture_packet.py",
        "data/pathspecs/ghostclaw_lane1_opus_architecture_packet_gate_2026-06-29.json",
        "docs/knowledge/SIRINX_GHOSTCLAW_LANE1_OPUS_ARCHITECTURE_PACKET_GATE_2026-06-29.md",
        "WORKSPACE_SCAFFOLD/tests/test_lane1_opus_architecture_packet_gate.py",
        "data/pathspecs/ghostclaw_lane1_opus_authoring_bundle_2026-06-29.json",
        "docs/knowledge/SIRINX_GHOSTCLAW_LANE1_OPUS_AUTHORING_BUNDLE_2026-06-29.md",
        "WORKSPACE_SCAFFOLD/tests/test_lane1_opus_authoring_bundle.py",
        "WORKSPACE_SCAFFOLD/tests/test_lane1_packet013_decision_draft.py",
    "data/pathspecs/ghostclaw_lane1_hermes_decision_transition_guard_2026-06-29.json",
    "docs/knowledge/SIRINX_GHOSTCLAW_LANE1_HERMES_DECISION_TRANSITION_GUARD_2026-06-29.md",
    "WORKSPACE_SCAFFOLD/scripts/build_lane1_hermes_decision_transition_guard.py",
    "WORKSPACE_SCAFFOLD/tests/test_lane1_hermes_decision_transition_guard.py",
    "data/pathspecs/ghostclaw_lane1_hermes_decision_intake_handoff_2026-06-29.json",
    "docs/knowledge/SIRINX_GHOSTCLAW_LANE1_HERMES_DECISION_INTAKE_HANDOFF_2026-06-29.md",
    "WORKSPACE_SCAFFOLD/scripts/build_lane1_hermes_decision_intake_handoff.py",
    "WORKSPACE_SCAFFOLD/tests/test_lane1_hermes_decision_intake_handoff.py",
    "WORKSPACE_SCAFFOLD/tests/test_lane1_hermes_decision_handoff_packet.py",
    "data/pathspecs/sirinx_r0_gate_specific_approval_contract_2026-06-29.json",
    "data/pathspecs/sirinx_all_chat_export_intake_mapper_2026-06-29.json",
    "data/pathspecs/sirinx_codex_hermes_work_report_contract_2026-06-29.json",
    "docs/knowledge/SIRINX_CODEX_HERMES_WORK_REPORT_DRAFT_2026-06-29.md",
    "_A2A_QUEUE/outbox/packet_014_codex_hermes_work_report_draft.json",
    "docs/knowledge/SIRINX_CODEX_HERMES_WORK_REPORT_PACKET_2026-06-29.md",
    "WORKSPACE_SCAFFOLD/manifests/active_goal_local_evidence_durability_2026-06-29.json",
    "docs/knowledge/SIRINX_ACTIVE_GOAL_LOCAL_EVIDENCE_DURABILITY_MANIFEST_2026-06-29.md",
    "WORKSPACE_SCAFFOLD/scripts/build_codex_hermes_work_report.py",
    "WORKSPACE_SCAFFOLD/scripts/validate_active_goal_blocker_clearance.py",
    "WORKSPACE_SCAFFOLD/scripts/validate_ghostclaw_v3_3_artifact_gate.py",
    "WORKSPACE_SCAFFOLD/tests/test_codex_hermes_execution_queue.py",
  ],
  nextAction:
    "Use the ordered local queue; Hermes records a separate packet_013 decision before any Codex recorder or LANE_2 action.",
};

export const GOD_MODE_CODEX_HERMES_A2A_QUEUE_STATUS: GodModeCodexHermesA2AQueueStatus = {
  status: "local_queue_indexed_not_executed",
  evidenceBoundary: "local_file_bus_only",
  currentActionablePacket: "packet_013",
  currentActionablePacketFolder: "inbox",
  runtimeQueueExecution: false,
  hermesDecisionRecorded: false,
  lane2Authorized: false,
  externalWrites: false,
  packetCounts: {
    inbox: 5,
    outbox: 15,
    working: 1,
    done: 8,
    blocked: 0,
    total: 29,
  },
  evidenceFiles: [
    "data/pathspecs/sirinx_codex_hermes_a2a_queue_status_2026-06-29.json",
    "docs/knowledge/SIRINX_CODEX_HERMES_A2A_QUEUE_STATUS_2026-06-29.md",
    "WORKSPACE_SCAFFOLD/reports/codex_hermes_a2a_queue_status_latest_2026-06-29.json",
    "WORKSPACE_SCAFFOLD/scripts/build_codex_hermes_a2a_queue_status.py",
    "WORKSPACE_SCAFFOLD/tests/test_codex_hermes_a2a_queue_status.py",
    "_A2A_QUEUE/outbox/packet_016_ghostclaw_lane1_hermes_decision_intake_handoff.json",
    "_A2A_QUEUE/outbox/packet_017_ghostclaw_lane1_hermes_decision_preflight_audit.json",
    "_A2A_QUEUE/outbox/packet_018_ghostclaw_lane1_opus_architecture_packet_gate.json",
    "_A2A_QUEUE/outbox/packet_019_ghostclaw_lane1_opus_authoring_bundle.json",
    "_A2A_QUEUE/outbox/packet_020_sirinx_all_chat_export_request.json",
    "_A2A_QUEUE/outbox/packet_021_sirinx_a2a_adaptive_sync_control_status.json",
    "_A2A_QUEUE/outbox/packet_022_sirinx_a2a_next_safe_action_sequencer.json",
    "_A2A_QUEUE/outbox/packet_023_sirinx_hermes_gateway_current_recheck.json",
    "_A2A_QUEUE/inbox/packet_024_sirinx_hermes_a2a_codex_sync_all_jobs.json",
    "_A2A_QUEUE/outbox/packet_025_sirinx_browser_use_candidate_lane.json",
    "data/pathspecs/sirinx_all_chat_export_request_packet_2026-06-29.json",
    "docs/knowledge/SIRINX_ALL_CHAT_EXPORT_REQUEST_PACKET_2026-06-29.md",
    "data/pathspecs/sirinx_a2a_adaptive_sync_control_status_2026-06-29.json",
    "docs/knowledge/SIRINX_A2A_ADAPTIVE_SYNC_CONTROL_STATUS_2026-06-29.md",
    "WORKSPACE_SCAFFOLD/tests/test_a2a_adaptive_sync_control_status_packet.py",
    "data/pathspecs/sirinx_a2a_next_safe_action_sequencer_2026-06-29.json",
    "docs/knowledge/SIRINX_A2A_NEXT_SAFE_ACTION_SEQUENCER_2026-06-29.md",
    "WORKSPACE_SCAFFOLD/tests/test_a2a_next_safe_action_sequencer_packet.py",
    "data/pathspecs/sirinx_hermes_gateway_current_recheck_packet_2026-06-29.json",
    "docs/knowledge/SIRINX_HERMES_GATEWAY_CURRENT_RECHECK_PACKET_2026-06-29.md",
    "WORKSPACE_SCAFFOLD/tests/test_hermes_gateway_current_recheck_packet.py",
    "data/pathspecs/sirinx_hermes_a2a_codex_sync_all_jobs_packet_2026-06-29.json",
    "docs/knowledge/SIRINX_HERMES_A2A_CODEX_SYNC_ALL_JOBS_PACKET_2026-06-29.md",
    "data/pathspecs/sirinx_browser_use_candidate_lane_2026-06-29.json",
    "docs/knowledge/SIRINX_BROWSER_USE_CANDIDATE_LANE_2026-06-29.md",
    "WORKSPACE_SCAFFOLD/tests/test_browser_use_candidate_lane.py",
    "GHOSTCLAW/a2a-hermes-codex-bridge/command-intents.ts",
    "GHOSTCLAW/a2a-hermes-codex-bridge/command-intents.test.ts",
  ],
  nextAction:
    "Review packet_024 as local goal-command evidence and packet_023 as gateway evidence; use the file-bus snapshot for local Codex/Hermes coordination only.",
};

export const GOD_MODE_SECURITY_FLAGS = [
  { label: "Robin HOLD", detail: "dark-web OSINT prohibited" },
  { label: "MiniMax API BLOCKED", detail: "China National Intelligence Law 2017" },
  { label: "APPROVE_ injection defense", detail: "hashtag injection blocked in pipeline" },
  { label: "No auto-publish/deploy/push", detail: "all 8 R0 gates require human approval" },
  { label: "Pocket Hatchery safe scope", detail: "no gambling / loot box / cash-out / public signer exposure" },
] as const;

export const GOD_MODE_MODEL_ROUTING = [
  { score: "1-4", model: "deepseek-v4-flash", color: "#6366f1" },
  { score: "5-7", model: "qwen3.6-plus", color: "#3b82f6" },
  { score: "8-10", model: "Qwen3-Max / claude-sonnet", color: "#ec4899" },
  { score: "audit", model: "gemini-2.5-pro", color: "#10b981" },
] as const;

export const GOD_MODE_AGENTS = [
  {
    tier: "L1 - CEO",
    color: "#f59e0b",
    list: ["Pitoon Yingyosruangrong (Human Owner / SIRINX)"],
  },
  {
    tier: "L2 - Directors",
    color: "#ec4899",
    list: ["Strategy Director", "Operations Director", "Creative Director"],
  },
  {
    tier: "L3 - Departmental (15)",
    color: "#3b82f6",
    list: [
      "Hermes (comms/router)",
      "Solar BI Agent",
      "Tax Shield Agent",
      "EV/BESS Agent",
      "PPA/Zero CapEx Agent",
      "Hotel Sector Agent",
      "Hospital Sector Agent",
      "Factory Sector Agent",
      "AGM Galaxy Agent",
      "Legal/Compliance Agent",
      "Finance/ROI Agent",
      "Marketing Agent",
      "R&D/AI Agent",
      "HR Agent",
      "Customer Success Agent",
    ],
  },
  {
    tier: "L4 - Cross-cutting (3)",
    color: "#10b981",
    list: ["Security Auditor", "Night Watch Monitor", "Memory / Psi Vault Keeper"],
  },
] as const;

export const GOD_MODE_INFRA_ENDPOINTS = [
  { name: "LiteLLM", port: ":4000" },
  { name: "Qwen3-35B", port: ":8080" },
  { name: "MySQL", port: ":3310" },
  { name: "n8n", port: ":5678" },
  { name: "Ollama", port: ":11434" },
  { name: "Redis", port: ":6379" },
] as const;

export const GOD_MODE_SOLAR_TARIFFS = [
  { label: "Peak", value: "4.18 THB/kWh", color: "#ef4444" },
  { label: "Off-peak", value: "2.65 THB/kWh", color: "#3b82f6" },
  { label: "VSPP", value: "2.20 THB/kWh", color: "#10b981" },
] as const;

export const GOD_MODE_PRIORITY_COLORS: Record<GodModePriority, string> = {
  P0: "#ef4444",
  P1: "#f97316",
  P2: "#f59e0b",
  P3: "#3b82f6",
  P4: "#7c3aed",
};

export const GOD_MODE_STATUS_COLORS: Record<GodModeLayerStatus | GodModeTaskStatus, string> = {
  active: "#10b981",
  blocked: "#ef4444",
  done: "#10b981",
  planned: "#3b82f6",
  "r0-gate": "#f59e0b",
  todo: "#475569",
  unknown: "#475569",
};

export function getGodModeLayer(id: GodModeLayerId): GodModeLayer | undefined {
  return GOD_MODE_LAYERS.find((layer) => layer.id === id);
}

export function getGodModeQueueSummary(queue: GodModeTask[] = GOD_MODE_QUEUE): GodModeQueueSummary {
  return {
    total: queue.length,
    blocked: queue.filter((task) => task.status === "blocked").length,
    r0Gated: queue.filter((task) => task.status === "r0-gate").length,
  };
}
