export type CorporateLayer =
  | "board"
  | "committee"
  | "c_suite"
  | "corporate_control"
  | "business_unit"
  | "shared_service"
  | "delivery";

export type ApprovalTier = "L0_READ" | "L1_INTERNAL_WRITE" | "L2_PUBLIC" | "L3_SENSITIVE";

export interface CompanyRole {
  id: string;
  title: string;
  thaiTitle: string;
  division: string;
  layer: CorporateLayer;
  reportsTo?: string;
  approvalTier: ApprovalTier;
  responsibilities: string[];
}

export const ENTERPRISE_AI_COMPANY_ROLES: CompanyRole[] = [
  {
    id: "chairperson",
    title: "Chairperson of the Board",
    thaiTitle: "ประธานกรรมการบริษัท",
    division: "Board of Directors",
    layer: "board",
    approvalTier: "L3_SENSITIVE",
    responsibilities: ["board agenda", "shareholder trust", "CEO oversight"],
  },
  {
    id: "independent_director",
    title: "Independent Director",
    thaiTitle: "กรรมการอิสระ",
    division: "Board of Directors",
    layer: "board",
    approvalTier: "L3_SENSITIVE",
    responsibilities: ["minority shareholder protection", "conflict review", "governance challenge"],
  },
  {
    id: "audit_committee_chair",
    title: "Audit Committee Chair",
    thaiTitle: "ประธานกรรมการตรวจสอบ",
    division: "Audit Committee",
    layer: "committee",
    approvalTier: "L3_SENSITIVE",
    responsibilities: ["financial controls", "audit plan", "internal control sign-off"],
  },
  {
    id: "risk_committee_chair",
    title: "Risk Committee Chair",
    thaiTitle: "ประธานกรรมการบริหารความเสี่ยง",
    division: "Risk Committee",
    layer: "committee",
    approvalTier: "L3_SENSITIVE",
    responsibilities: ["enterprise risk appetite", "AI risk register", "incident escalation"],
  },
  {
    id: "nomination_compensation_chair",
    title: "Nomination and Compensation Committee Chair",
    thaiTitle: "ประธานกรรมการสรรหาและกำหนดค่าตอบแทน",
    division: "Nomination and Compensation Committee",
    layer: "committee",
    approvalTier: "L3_SENSITIVE",
    responsibilities: ["executive succession", "compensation policy", "board evaluation"],
  },
  {
    id: "ceo",
    title: "Chief Executive Officer",
    thaiTitle: "ประธานเจ้าหน้าที่บริหาร",
    division: "Executive Office",
    layer: "c_suite",
    reportsTo: "chairperson",
    approvalTier: "L3_SENSITIVE",
    responsibilities: ["company strategy", "capital allocation", "public accountability"],
  },
  {
    id: "coo",
    title: "Chief Operating Officer",
    thaiTitle: "ประธานเจ้าหน้าที่ปฏิบัติการ",
    division: "Operations",
    layer: "c_suite",
    reportsTo: "ceo",
    approvalTier: "L2_PUBLIC",
    responsibilities: ["operating cadence", "delivery quality", "cross-functional execution"],
  },
  {
    id: "cfo",
    title: "Chief Financial Officer",
    thaiTitle: "ประธานเจ้าหน้าที่การเงิน",
    division: "Finance",
    layer: "c_suite",
    reportsTo: "ceo",
    approvalTier: "L3_SENSITIVE",
    responsibilities: ["budget", "cash flow", "financial reporting"],
  },
  {
    id: "cto",
    title: "Chief Technology Officer",
    thaiTitle: "ประธานเจ้าหน้าที่เทคโนโลยี",
    division: "Technology",
    layer: "c_suite",
    reportsTo: "ceo",
    approvalTier: "L2_PUBLIC",
    responsibilities: ["technical architecture", "platform reliability", "engineering standards"],
  },
  {
    id: "caio",
    title: "Chief AI Officer",
    thaiTitle: "ประธานเจ้าหน้าที่ปัญญาประดิษฐ์",
    division: "AI Office",
    layer: "c_suite",
    reportsTo: "ceo",
    approvalTier: "L2_PUBLIC",
    responsibilities: ["agent strategy", "model routing", "AI governance"],
  },
  {
    id: "ciso",
    title: "Chief Information Security Officer",
    thaiTitle: "ประธานเจ้าหน้าที่ความมั่นคงปลอดภัยสารสนเทศ",
    division: "Security",
    layer: "c_suite",
    reportsTo: "ceo",
    approvalTier: "L3_SENSITIVE",
    responsibilities: ["security policy", "incident response", "secret handling"],
  },
  {
    id: "clo",
    title: "Chief Legal Officer",
    thaiTitle: "ประธานเจ้าหน้าที่กฎหมาย",
    division: "Legal",
    layer: "c_suite",
    reportsTo: "ceo",
    approvalTier: "L3_SENSITIVE",
    responsibilities: ["contracts", "regulatory review", "public disclosure risk"],
  },
  {
    id: "cpo",
    title: "Chief Product Officer",
    thaiTitle: "ประธานเจ้าหน้าที่ผลิตภัณฑ์",
    division: "Product",
    layer: "c_suite",
    reportsTo: "ceo",
    approvalTier: "L2_PUBLIC",
    responsibilities: ["product strategy", "roadmap", "customer value"],
  },
  {
    id: "cro",
    title: "Chief Revenue Officer",
    thaiTitle: "ประธานเจ้าหน้าที่รายได้",
    division: "Revenue",
    layer: "c_suite",
    reportsTo: "ceo",
    approvalTier: "L2_PUBLIC",
    responsibilities: ["sales pipeline", "pricing", "go-to-market"],
  },
  {
    id: "chro",
    title: "Chief Human Resources Officer",
    thaiTitle: "ประธานเจ้าหน้าที่ทรัพยากรบุคคล",
    division: "People",
    layer: "c_suite",
    reportsTo: "ceo",
    approvalTier: "L2_PUBLIC",
    responsibilities: ["talent strategy", "culture", "performance system"],
  },
  {
    id: "cmo",
    title: "Chief Marketing Officer",
    thaiTitle: "ประธานเจ้าหน้าที่การตลาด",
    division: "Marketing",
    layer: "c_suite",
    reportsTo: "ceo",
    approvalTier: "L2_PUBLIC",
    responsibilities: ["brand", "content engine", "demand generation"],
  },
  {
    id: "cio",
    title: "Chief Information Officer",
    thaiTitle: "ประธานเจ้าหน้าที่สารสนเทศ",
    division: "IT",
    layer: "c_suite",
    reportsTo: "ceo",
    approvalTier: "L2_PUBLIC",
    responsibilities: ["internal systems", "SaaS governance", "business data flow"],
  },
  {
    id: "head_internal_audit",
    title: "Head of Internal Audit",
    thaiTitle: "ผู้อำนวยการตรวจสอบภายใน",
    division: "Internal Audit",
    layer: "corporate_control",
    reportsTo: "audit_committee_chair",
    approvalTier: "L3_SENSITIVE",
    responsibilities: ["audit evidence", "control testing", "board reporting"],
  },
  {
    id: "head_compliance",
    title: "Head of Compliance",
    thaiTitle: "ผู้อำนวยการกำกับดูแลการปฏิบัติตามกฎ",
    division: "Compliance",
    layer: "corporate_control",
    reportsTo: "clo",
    approvalTier: "L3_SENSITIVE",
    responsibilities: ["policy checks", "regulatory obligations", "approval gates"],
  },
  {
    id: "head_risk",
    title: "Head of Enterprise Risk",
    thaiTitle: "ผู้อำนวยการบริหารความเสี่ยงองค์กร",
    division: "Risk",
    layer: "corporate_control",
    reportsTo: "risk_committee_chair",
    approvalTier: "L3_SENSITIVE",
    responsibilities: ["risk register", "scenario planning", "risk acceptance"],
  },
  {
    id: "head_ir",
    title: "Head of Investor Relations",
    thaiTitle: "ผู้อำนวยการนักลงทุนสัมพันธ์",
    division: "Investor Relations",
    layer: "corporate_control",
    reportsTo: "cfo",
    approvalTier: "L3_SENSITIVE",
    responsibilities: ["investor updates", "disclosure calendar", "market messaging"],
  },
  {
    id: "corporate_secretary",
    title: "Corporate Secretary",
    thaiTitle: "เลขานุการบริษัท",
    division: "Governance",
    layer: "corporate_control",
    reportsTo: "chairperson",
    approvalTier: "L3_SENSITIVE",
    responsibilities: ["board minutes", "AGM materials", "governance records"],
  },
  {
    id: "controller",
    title: "Financial Controller",
    thaiTitle: "ผู้ควบคุมบัญชีการเงิน",
    division: "Finance",
    layer: "shared_service",
    reportsTo: "cfo",
    approvalTier: "L2_PUBLIC",
    responsibilities: ["closing process", "management accounts", "ledger quality"],
  },
  {
    id: "treasury_lead",
    title: "Treasury Lead",
    thaiTitle: "หัวหน้าฝ่ายบริหารเงิน",
    division: "Finance",
    layer: "shared_service",
    reportsTo: "cfo",
    approvalTier: "L3_SENSITIVE",
    responsibilities: ["cash planning", "bank coordination", "liquidity risk"],
  },
  {
    id: "tax_lead",
    title: "Tax Lead",
    thaiTitle: "หัวหน้าฝ่ายภาษี",
    division: "Finance",
    layer: "shared_service",
    reportsTo: "cfo",
    approvalTier: "L2_PUBLIC",
    responsibilities: ["tax filing", "tax risk", "incentive planning"],
  },
  {
    id: "vp_engineering",
    title: "VP Engineering",
    thaiTitle: "รองประธานฝ่ายวิศวกรรม",
    division: "Technology",
    layer: "business_unit",
    reportsTo: "cto",
    approvalTier: "L2_PUBLIC",
    responsibilities: ["engineering delivery", "code quality", "technical hiring"],
  },
  {
    id: "platform_architect",
    title: "Platform Architect",
    thaiTitle: "สถาปนิกแพลตฟอร์ม",
    division: "Technology",
    layer: "delivery",
    reportsTo: "cto",
    approvalTier: "L2_PUBLIC",
    responsibilities: ["system design", "integration boundaries", "scalability"],
  },
  {
    id: "agent_runtime_lead",
    title: "Agent Runtime Lead",
    thaiTitle: "หัวหน้าระบบรันไทม์เอเจนต์",
    division: "AI Office",
    layer: "delivery",
    reportsTo: "caio",
    approvalTier: "L2_PUBLIC",
    responsibilities: ["agent registry", "tool routing", "memory policy"],
  },
  {
    id: "model_routing_lead",
    title: "Model Routing Lead",
    thaiTitle: "หัวหน้าการเลือกและจัดเส้นทางโมเดล",
    division: "AI Office",
    layer: "delivery",
    reportsTo: "caio",
    approvalTier: "L2_PUBLIC",
    responsibilities: ["cost-aware routing", "provider evaluation", "fallback policy"],
  },
  {
    id: "ai_safety_lead",
    title: "AI Safety Lead",
    thaiTitle: "หัวหน้าความปลอดภัยปัญญาประดิษฐ์",
    division: "AI Office",
    layer: "corporate_control",
    reportsTo: "caio",
    approvalTier: "L3_SENSITIVE",
    responsibilities: ["guardrails", "red-team review", "public-output approval"],
  },
  {
    id: "data_platform_lead",
    title: "Data Platform Lead",
    thaiTitle: "หัวหน้าแพลตฟอร์มข้อมูล",
    division: "Data",
    layer: "delivery",
    reportsTo: "cio",
    approvalTier: "L2_PUBLIC",
    responsibilities: ["data pipelines", "quality checks", "analytics readiness"],
  },
  {
    id: "knowledge_vault_lead",
    title: "Knowledge Vault Lead",
    thaiTitle: "หัวหน้าคลังความรู้องค์กร",
    division: "Data",
    layer: "delivery",
    reportsTo: "caio",
    approvalTier: "L1_INTERNAL_WRITE",
    responsibilities: ["knowledge cards", "SOP extraction", "memory distillation"],
  },
  {
    id: "product_director",
    title: "Product Director",
    thaiTitle: "ผู้อำนวยการผลิตภัณฑ์",
    division: "Product",
    layer: "business_unit",
    reportsTo: "cpo",
    approvalTier: "L2_PUBLIC",
    responsibilities: ["product discovery", "market fit", "release scope"],
  },
  {
    id: "ux_director",
    title: "UX Director",
    thaiTitle: "ผู้อำนวยการประสบการณ์ผู้ใช้",
    division: "Design",
    layer: "business_unit",
    reportsTo: "cpo",
    approvalTier: "L2_PUBLIC",
    responsibilities: ["research", "design systems", "user journey"],
  },
  {
    id: "qa_director",
    title: "QA Director",
    thaiTitle: "ผู้อำนวยการประกันคุณภาพ",
    division: "Quality",
    layer: "business_unit",
    reportsTo: "coo",
    approvalTier: "L2_PUBLIC",
    responsibilities: ["test strategy", "release gates", "defect trends"],
  },
  {
    id: "devops_lead",
    title: "DevOps Lead",
    thaiTitle: "หัวหน้าปฏิบัติการระบบ",
    division: "Technology",
    layer: "delivery",
    reportsTo: "cto",
    approvalTier: "L3_SENSITIVE",
    responsibilities: ["deployment plan", "rollback", "runtime health"],
  },
  {
    id: "security_engineering_lead",
    title: "Security Engineering Lead",
    thaiTitle: "หัวหน้าวิศวกรรมความปลอดภัย",
    division: "Security",
    layer: "delivery",
    reportsTo: "ciso",
    approvalTier: "L3_SENSITIVE",
    responsibilities: ["secure SDLC", "secret scanning", "vulnerability response"],
  },
  {
    id: "privacy_officer",
    title: "Privacy Officer",
    thaiTitle: "เจ้าหน้าที่คุ้มครองข้อมูลส่วนบุคคล",
    division: "Legal",
    layer: "corporate_control",
    reportsTo: "clo",
    approvalTier: "L3_SENSITIVE",
    responsibilities: ["PDPA review", "data minimization", "privacy incident routing"],
  },
  {
    id: "sales_director",
    title: "Sales Director",
    thaiTitle: "ผู้อำนวยการฝ่ายขาย",
    division: "Revenue",
    layer: "business_unit",
    reportsTo: "cro",
    approvalTier: "L2_PUBLIC",
    responsibilities: ["pipeline management", "deal desk", "sales forecast"],
  },
  {
    id: "marketing_director",
    title: "Marketing Director",
    thaiTitle: "ผู้อำนวยการการตลาด",
    division: "Marketing",
    layer: "business_unit",
    reportsTo: "cmo",
    approvalTier: "L2_PUBLIC",
    responsibilities: ["campaigns", "content calendar", "brand consistency"],
  },
  {
    id: "customer_success_director",
    title: "Customer Success Director",
    thaiTitle: "ผู้อำนวยการดูแลความสำเร็จลูกค้า",
    division: "Customer Success",
    layer: "business_unit",
    reportsTo: "coo",
    approvalTier: "L2_PUBLIC",
    responsibilities: ["retention", "onboarding", "customer health"],
  },
  {
    id: "delivery_director",
    title: "Delivery Director",
    thaiTitle: "ผู้อำนวยการส่งมอบงาน",
    division: "Delivery",
    layer: "business_unit",
    reportsTo: "coo",
    approvalTier: "L2_PUBLIC",
    responsibilities: ["project delivery", "scope control", "client acceptance"],
  },
  {
    id: "support_lead",
    title: "Support Lead",
    thaiTitle: "หัวหน้าทีมสนับสนุนลูกค้า",
    division: "Customer Success",
    layer: "delivery",
    reportsTo: "customer_success_director",
    approvalTier: "L1_INTERNAL_WRITE",
    responsibilities: ["ticket triage", "SLA monitoring", "support playbooks"],
  },
  {
    id: "people_ops_lead",
    title: "People Operations Lead",
    thaiTitle: "หัวหน้าปฏิบัติการบุคคล",
    division: "People",
    layer: "shared_service",
    reportsTo: "chro",
    approvalTier: "L2_PUBLIC",
    responsibilities: ["hiring process", "employee lifecycle", "policy communication"],
  },
  {
    id: "learning_director",
    title: "Learning and Academy Director",
    thaiTitle: "ผู้อำนวยการเรียนรู้และอะคาเดมี",
    division: "Academy",
    layer: "business_unit",
    reportsTo: "chro",
    approvalTier: "L2_PUBLIC",
    responsibilities: ["AI Academy", "course curriculum", "certification paths"],
  },
  {
    id: "procurement_lead",
    title: "Procurement Lead",
    thaiTitle: "หัวหน้าจัดซื้อจัดจ้าง",
    division: "Operations",
    layer: "shared_service",
    reportsTo: "coo",
    approvalTier: "L2_PUBLIC",
    responsibilities: ["vendor selection", "purchase approval", "contract handoff"],
  },
  {
    id: "project_management_office",
    title: "PMO Lead",
    thaiTitle: "หัวหน้าสำนักงานบริหารโครงการ",
    division: "Operations",
    layer: "shared_service",
    reportsTo: "coo",
    approvalTier: "L2_PUBLIC",
    responsibilities: ["portfolio visibility", "timeline risk", "executive reporting"],
  },
  {
    id: "business_automation_lead",
    title: "Business Automation Lead",
    thaiTitle: "หัวหน้าระบบอัตโนมัติธุรกิจ",
    division: "Automation Studio",
    layer: "delivery",
    reportsTo: "coo",
    approvalTier: "L2_PUBLIC",
    responsibilities: ["CRM automation", "quotation flow", "workflow SOP"],
  },
  {
    id: "content_engine_lead",
    title: "Content Engine Lead",
    thaiTitle: "หัวหน้าระบบคอนเทนต์",
    division: "Marketing",
    layer: "delivery",
    reportsTo: "cmo",
    approvalTier: "L2_PUBLIC",
    responsibilities: ["content repurposing", "video scripts", "prompt library"],
  },
  {
    id: "brand_director",
    title: "Brand Director",
    thaiTitle: "ผู้อำนวยการแบรนด์",
    division: "Marketing",
    layer: "business_unit",
    reportsTo: "cmo",
    approvalTier: "L2_PUBLIC",
    responsibilities: ["Ghost Claws brand", "SIRINXDev brand", "visual quality"],
  },
  {
    id: "line_oa_crm_lead",
    title: "LINE OA and CRM Lead",
    thaiTitle: "หัวหน้า LINE OA และ CRM",
    division: "Revenue Operations",
    layer: "delivery",
    reportsTo: "cro",
    approvalTier: "L2_PUBLIC",
    responsibilities: ["lead capture", "LINE OA flow", "follow-up routing"],
  },
  {
    id: "quotation_system_lead",
    title: "Quotation System Lead",
    thaiTitle: "หัวหน้าระบบใบเสนอราคา",
    division: "Revenue Operations",
    layer: "delivery",
    reportsTo: "cro",
    approvalTier: "L2_PUBLIC",
    responsibilities: ["quotation draft", "owner approval", "PDF generation"],
  },
  {
    id: "research_lead",
    title: "Research Lead",
    thaiTitle: "หัวหน้าวิจัย",
    division: "Research",
    layer: "business_unit",
    reportsTo: "caio",
    approvalTier: "L1_INTERNAL_WRITE",
    responsibilities: ["AI research scan", "technical evaluation", "opportunity mapping"],
  },
  {
    id: "ethics_officer",
    title: "AI Ethics Officer",
    thaiTitle: "เจ้าหน้าที่จริยธรรมปัญญาประดิษฐ์",
    division: "Governance",
    layer: "corporate_control",
    reportsTo: "risk_committee_chair",
    approvalTier: "L3_SENSITIVE",
    responsibilities: ["ethical review", "bias risk", "public trust"],
  },
];

export const PUBLIC_COMPANY_APPROVAL_RULES = {
  L0_READ: ["summarize", "read status", "draft internal brief"],
  L1_INTERNAL_WRITE: ["save internal draft", "create task", "create knowledge card"],
  L2_PUBLIC: ["publish content", "update website", "send quotation draft after owner approval"],
  L3_SENSITIVE: ["deploy production", "change DNS", "read customer data", "approve public disclosure"],
} as const;
